services:

  mysql:
    image: mysql:9.3.0
    container_name: events_manager_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pluto
      MYSQL_DATABASE: events_manager
    ports: 
      - 3311:3306
    volumes:
      - events_manager_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      
volumes:
  events_manager_data: